/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem.system.analysis;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jishan
 */
public class AddTeacherInfo extends javax.swing.JFrame {

    /**
     * Creates new form AddTeacherInfo
     */
    public AddTeacherInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jBtnSave = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jtxtid = new javax.swing.JTextField();
        jtxtmna = new javax.swing.JTextField();
        jtxtfan = new javax.swing.JTextField();
        jtxtfn = new javax.swing.JTextField();
        jtxtgend = new javax.swing.JTextField();
        jtxtr2 = new javax.swing.JTextField();
        jtxts1 = new javax.swing.JTextField();
        jtxtb1 = new javax.swing.JTextField();
        jbtnbgroup = new javax.swing.JTextField();
        jtxtfull = new javax.swing.JTextField();
        jtxtdob = new javax.swing.JTextField();
        jtxtd1 = new javax.swing.JTextField();
        jtxtp1 = new javax.swing.JTextField();
        jtxtb2 = new javax.swing.JTextField();
        jtxtr1 = new javax.swing.JTextField();
        jtxtlnam = new javax.swing.JTextField();
        jbtnd2 = new javax.swing.JTextField();
        jbtngra = new javax.swing.JTextField();
        jbtnuder = new javax.swing.JTextField();
        jbtnhsc = new javax.swing.JTextField();
        jbtnssc = new javax.swing.JTextField();
        jbtncn = new javax.swing.JTextField();
        jbtns2 = new javax.swing.JTextField();
        jbtnp2 = new javax.swing.JTextField();
        jtxtdate1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SUNRISE PARISH PUBLIC SCHOOL SYSTEM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 0, 660, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel3.setText("Add Teacher Information");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 30, 310, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Teacher's ID Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 80, 190, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Teacher's Full Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 110, 150, 16);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Teacher's First Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 140, 160, 16);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Teacher's Last Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 170, 210, 16);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Date of Birth");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(160, 200, 140, 16);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(160, 230, 130, 16);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Father's Name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(160, 260, 120, 16);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Mother's Name");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(160, 290, 130, 16);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Plot No.");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(490, 380, 100, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("Section No.");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(490, 350, 110, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Present Address :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(160, 320, 160, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Road No.");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(260, 350, 90, 14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("Block No.");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(260, 380, 80, 14);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("District :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(340, 410, 70, 16);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("District :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(340, 520, 56, 16);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel22.setText("Road No.");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(260, 470, 57, 16);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel23.setText("Section No.");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(490, 470, 72, 16);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel24.setText("Block No.");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(260, 500, 57, 16);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel25.setText("Plot No.");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(490, 500, 49, 16);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setText("Permenant Address :");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(160, 440, 138, 16);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setText("Blood Group");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(160, 550, 120, 14);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel28.setText("Contact Number");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(160, 570, 104, 16);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel29.setText("Educational Qualification :");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(160, 590, 220, 16);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel30.setText("SSC");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(190, 610, 40, 16);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel31.setText("HSC");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(300, 610, 40, 16);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel32.setText("Graduate");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(410, 610, 60, 16);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel33.setText("Postgraduate");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(560, 610, 98, 16);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel34.setText("         © 2017 Sunrise Parish Public School System | All Rights Reserved By Sunrise School | Dhaka, Bangladesh-1208 | Phone +88-02-01977239551");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(80, 680, 620, 16);

        jBtnSave.setBackground(new java.awt.Color(0, 153, 153));
        jBtnSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnSave.setText("Save");
        jBtnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSave);
        jBtnSave.setBounds(30, 650, 73, 23);

        jBtnReset.setBackground(new java.awt.Color(0, 153, 153));
        jBtnReset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnReset.setText("Reset");
        jBtnReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnReset);
        jBtnReset.setBounds(240, 650, 70, 20);

        jBtnBack.setBackground(new java.awt.Color(0, 153, 153));
        jBtnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnBack.setText("Back");
        jBtnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnBack);
        jBtnBack.setBounds(450, 650, 70, 20);

        jBtnExit.setBackground(new java.awt.Color(0, 153, 153));
        jBtnExit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnExit.setText("Exit");
        jBtnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnExit);
        jBtnExit.setBounds(660, 650, 70, 20);

        jtxtid.setBackground(new java.awt.Color(204, 255, 204));
        jtxtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtid);
        jtxtid.setBounds(360, 80, 300, 18);

        jtxtmna.setBackground(new java.awt.Color(204, 255, 204));
        jtxtmna.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtmna.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtmna);
        jtxtmna.setBounds(360, 290, 300, 18);

        jtxtfan.setBackground(new java.awt.Color(204, 255, 204));
        jtxtfan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtfan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtfan);
        jtxtfan.setBounds(360, 260, 300, 18);

        jtxtfn.setBackground(new java.awt.Color(204, 255, 204));
        jtxtfn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtfn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtfn);
        jtxtfn.setBounds(360, 140, 300, 18);

        jtxtgend.setBackground(new java.awt.Color(204, 255, 204));
        jtxtgend.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtgend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtgend);
        jtxtgend.setBounds(360, 230, 300, 18);

        jtxtr2.setBackground(new java.awt.Color(204, 255, 204));
        jtxtr2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtr2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtr2);
        jtxtr2.setBounds(350, 470, 100, 18);

        jtxts1.setBackground(new java.awt.Color(204, 255, 204));
        jtxts1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxts1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxts1);
        jtxts1.setBounds(590, 350, 100, 18);

        jtxtb1.setBackground(new java.awt.Color(204, 255, 204));
        jtxtb1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtb1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtb1);
        jtxtb1.setBounds(350, 380, 100, 18);

        jbtnbgroup.setBackground(new java.awt.Color(204, 255, 204));
        jbtnbgroup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbtnbgroup.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jbtnbgroup);
        jbtnbgroup.setBounds(360, 550, 300, 18);

        jtxtfull.setBackground(new java.awt.Color(204, 255, 204));
        jtxtfull.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtfull.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtfull);
        jtxtfull.setBounds(360, 110, 300, 18);

        jtxtdob.setBackground(new java.awt.Color(204, 255, 204));
        jtxtdob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdob.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtdob);
        jtxtdob.setBounds(360, 200, 300, 18);

        jtxtd1.setBackground(new java.awt.Color(204, 255, 204));
        jtxtd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtd1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtd1);
        jtxtd1.setBounds(410, 410, 210, 18);

        jtxtp1.setBackground(new java.awt.Color(204, 255, 204));
        jtxtp1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtp1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtp1);
        jtxtp1.setBounds(590, 380, 100, 18);

        jtxtb2.setBackground(new java.awt.Color(204, 255, 204));
        jtxtb2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtb2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtb2);
        jtxtb2.setBounds(350, 500, 100, 18);

        jtxtr1.setBackground(new java.awt.Color(204, 255, 204));
        jtxtr1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtr1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtr1);
        jtxtr1.setBounds(350, 350, 100, 18);

        jtxtlnam.setBackground(new java.awt.Color(204, 255, 204));
        jtxtlnam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtlnam.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtlnam);
        jtxtlnam.setBounds(360, 170, 300, 18);

        jbtnd2.setBackground(new java.awt.Color(204, 255, 204));
        jbtnd2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbtnd2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jbtnd2);
        jbtnd2.setBounds(410, 520, 210, 20);

        jbtngra.setBackground(new java.awt.Color(204, 255, 204));
        jbtngra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbtngra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jbtngra);
        jbtngra.setBounds(480, 610, 65, 20);

        jbtnuder.setBackground(new java.awt.Color(204, 255, 204));
        jbtnuder.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbtnuder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jbtnuder);
        jbtnuder.setBounds(660, 610, 70, 20);

        jbtnhsc.setBackground(new java.awt.Color(204, 255, 204));
        jbtnhsc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbtnhsc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jbtnhsc);
        jbtnhsc.setBounds(340, 610, 65, 20);

        jbtnssc.setBackground(new java.awt.Color(204, 255, 204));
        jbtnssc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbtnssc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jbtnssc);
        jbtnssc.setBounds(220, 610, 65, 20);

        jbtncn.setBackground(new java.awt.Color(204, 255, 204));
        jbtncn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbtncn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jbtncn);
        jbtncn.setBounds(360, 570, 300, 20);

        jbtns2.setBackground(new java.awt.Color(204, 255, 204));
        jbtns2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbtns2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtns2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtns2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtns2);
        jbtns2.setBounds(590, 470, 100, 18);

        jbtnp2.setBackground(new java.awt.Color(204, 255, 204));
        jbtnp2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jbtnp2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jbtnp2);
        jbtnp2.setBounds(590, 500, 100, 18);

        jtxtdate1.setBackground(new java.awt.Color(204, 255, 204));
        jtxtdate1.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jtxtdate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jtxtdate1);
        jtxtdate1.setBounds(660, 50, 100, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("Date :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(610, 50, 50, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementsystem/system/analysis/home-banner-4.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 770, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/SystemAnalysis", "Jishan", "Jishan");
            PreparedStatement ps = conn.prepareStatement("insert into ADDTEACHERINFO values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, jtxtdate1.getText());
            ps.setString(2, jtxtid.getText());
            ps.setString(3, jtxtfull.getText());
            ps.setString(4, jtxtfn.getText());
            ps.setString(5, jtxtlnam.getText());
            ps.setString(6, jtxtdob.getText());
            ps.setString(7, jtxtgend.getText());
            ps.setString(8, jtxtfan.getText());
            ps.setString(9, jtxtmna.getText());
            ps.setString(10, jtxtr1.getText());
            ps.setString(11, jtxts1.getText());
            ps.setString(12, jtxtb1.getText());
            ps.setString(13, jtxtp1.getText());
            ps.setString(14,  jtxtd1.getText());
            ps.setString(15, jtxtr2.getText());
            ps.setString(16, jbtns2.getText());
            ps.setString(17, jtxtb2.getText());
            ps.setString(18, jbtnp2.getText());
            ps.setString(19, jbtnd2.getText());
            ps.setString(20, jbtnbgroup.getText());
            ps.setString(21, jbtncn.getText());
            ps.setString(22, jbtnssc.getText());
            ps.setString(23, jbtnhsc.getText());
            ps.setString(24, jbtngra.getText());
            ps.setString(25, jbtnuder.getText());
            ps.executeUpdate();
            conn.close();
            JOptionPane.showMessageDialog(null, "Congratulations...!!! \nYour data has been successfully store in our database...!!! \nThank you for using student management system...!!!");
            System.out.println("Congratulations...!!! Data save successfully...!!!");
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        this.hide();
        Interface frm = new Interface();
        frm.setVisible(true);
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jbtns2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtns2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtns2ActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        jtxtdate1.setText(null);
        jtxtid.setText(null);
        jtxtfull.setText(null);
        jtxtfn.setText(null);
        jtxtlnam.setText(null);
        jtxtdob.setText(null);
        jtxtgend.setText(null);
        jtxtfan.setText(null);
        jtxtmna.setText(null);
        jtxtr1.setText(null);
        jtxts1.setText(null);
        jtxtb1.setText(null);
        jtxtp1.setText(null);
        jtxtd1.setText(null);
        jtxtr2.setText(null);
        jbtns2.setText(null);
        jtxtb2.setText(null);
        jbtnp2.setText(null);
        jbtnd2.setText(null);
        jbtnbgroup.setText(null);
        jbtncn.setText(null);
        jbtnssc.setText(null);
        jbtnhsc.setText(null);
        jbtngra.setText(null);
        jbtnuder.setText(null);
    }//GEN-LAST:event_jBtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeacherInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeacherInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeacherInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeacherInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTeacherInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jbtnbgroup;
    private javax.swing.JTextField jbtncn;
    private javax.swing.JTextField jbtnd2;
    private javax.swing.JTextField jbtngra;
    private javax.swing.JTextField jbtnhsc;
    private javax.swing.JTextField jbtnp2;
    private javax.swing.JTextField jbtns2;
    private javax.swing.JTextField jbtnssc;
    private javax.swing.JTextField jbtnuder;
    private javax.swing.JTextField jtxtb1;
    private javax.swing.JTextField jtxtb2;
    private javax.swing.JTextField jtxtd1;
    private javax.swing.JTextField jtxtdate1;
    private javax.swing.JTextField jtxtdob;
    private javax.swing.JTextField jtxtfan;
    private javax.swing.JTextField jtxtfn;
    private javax.swing.JTextField jtxtfull;
    private javax.swing.JTextField jtxtgend;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtlnam;
    private javax.swing.JTextField jtxtmna;
    private javax.swing.JTextField jtxtp1;
    private javax.swing.JTextField jtxtr1;
    private javax.swing.JTextField jtxtr2;
    private javax.swing.JTextField jtxts1;
    // End of variables declaration//GEN-END:variables
}
