/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem.system.analysis;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jishan
 */
public class Attendance extends javax.swing.JFrame {

    /**
     * Creates new form Attendance
     */
    public Attendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtdate6564 = new javax.swing.JTextField();
        jtxtyear = new javax.swing.JTextField();
        jtxtday = new javax.swing.JTextField();
        jtxtsemester = new javax.swing.JTextField();
        jtxtat = new javax.swing.JTextField();
        jtxtdt = new javax.swing.JTextField();
        jtxttake = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtxtdate1 = new javax.swing.JTextField();
        jtxtreat1 = new javax.swing.JTextField();
        jtxtsemester1 = new javax.swing.JTextField();
        jtxtattim = new javax.swing.JTextField();
        jtxtattejhj = new javax.swing.JTextField();
        jtxtday2 = new javax.swing.JTextField();
        jtxtdddep = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jbtnsave = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jbtnexit = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SUNRISE PARISH PUBLIC SCHOOL SYSTEM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 0, 620, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Attendance Section");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 30, 340, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teacher Part :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 100, 150, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 130, 38, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Day");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(460, 130, 20, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Semester");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 210, 52, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Year");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 170, 25, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Number of Taking Class");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 250, 127, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Deparature Time");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(460, 210, 92, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Arrival Time");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(460, 170, 63, 15);

        jtxtdate6564.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdate6564.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtdate6564);
        jtxtdate6564.setBounds(190, 130, 210, 18);

        jtxtyear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtyear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtyear);
        jtxtyear.setBounds(190, 170, 210, 18);

        jtxtday.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtday.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtday);
        jtxtday.setBounds(500, 130, 220, 18);

        jtxtsemester.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsemester.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsemester);
        jtxtsemester.setBounds(190, 210, 210, 18);

        jtxtat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtat);
        jtxtat.setBounds(540, 170, 180, 18);

        jtxtdt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtdt);
        jtxtdt.setBounds(560, 210, 160, 18);

        jtxttake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxttake.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxttake);
        jtxttake.setBounds(270, 250, 450, 18);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Student Part :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 300, 140, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(130, 340, 26, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Day");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(460, 340, 45, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Deparature Time");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(460, 420, 92, 15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Arrival Time");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(460, 380, 63, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Semester");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(130, 420, 70, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Year");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(130, 380, 25, 15);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Number of Attending Class ");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(130, 460, 170, 14);

        jtxtdate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdate1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtdate1);
        jtxtdate1.setBounds(190, 340, 210, 18);

        jtxtreat1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtreat1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtreat1);
        jtxtreat1.setBounds(190, 380, 210, 18);

        jtxtsemester1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsemester1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsemester1);
        jtxtsemester1.setBounds(190, 420, 210, 20);

        jtxtattim.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtattim.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtattim);
        jtxtattim.setBounds(540, 380, 180, 18);

        jtxtattejhj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtattejhj.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtattejhj);
        jtxtattejhj.setBounds(290, 460, 430, 18);

        jtxtday2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtday2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtday2);
        jtxtday2.setBounds(510, 340, 210, 18);

        jtxtdddep.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdddep.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtdddep);
        jtxtdddep.setBounds(560, 420, 160, 18);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("         © 2017 Sunrise Parish Public School System | All Rights Reserved By Sunrise School | Dhaka, Bangladesh-1208 | Phone +88-02-01977239551");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(80, 540, 650, 13);

        jbtnsave.setBackground(new java.awt.Color(0, 102, 102));
        jbtnsave.setText("Save");
        jbtnsave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnsave);
        jbtnsave.setBounds(30, 500, 90, 20);

        jbtnreset.setBackground(new java.awt.Color(0, 102, 102));
        jbtnreset.setText("Reset");
        jbtnreset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnreset);
        jbtnreset.setBounds(230, 500, 90, 20);

        jbtnexit.setBackground(new java.awt.Color(0, 102, 102));
        jbtnexit.setText("Exit");
        jbtnexit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnexit);
        jbtnexit.setBounds(630, 500, 90, 20);

        jbtnback.setBackground(new java.awt.Color(0, 102, 102));
        jbtnback.setText("Back");
        jbtnback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnback);
        jbtnback.setBounds(440, 500, 90, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementsystem/system/analysis/ttght.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsaveActionPerformed
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/SystemAnalysis", "Jishan", "Jishan");
            PreparedStatement ps = conn.prepareStatement("insert into Attendance values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, jtxtdate6564.getText());
            ps.setString(2, jtxtday.getText());
            ps.setString(3, jtxtyear.getText());
            ps.setString(4, jtxtat.getText());
            ps.setString(5, jtxtsemester.getText());
            ps.setString(6, jtxtdt.getText());
            ps.setString(7, jtxttake.getText());
            ps.setString(8, jtxtdate1.getText());
            ps.setString(9, jtxtday2.getText());
            ps.setString(10, jtxtreat1.getText());
            ps.setString(11, jtxtattim.getText());
            ps.setString(12, jtxtsemester1.getText());
            ps.setString(13, jtxtdddep.getText());
            ps.setString(14, jtxtattejhj.getText());
            ps.executeUpdate();
            conn.close();
            JOptionPane.showMessageDialog(null, "Congratulations...!!! \nYour data has been successfully store in our database...!!! \nThank you for using student management system...!!!");
            System.out.println("Congratulations...!!! Data save successfully...!!!");
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnsaveActionPerformed

    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        jtxtdate6564.setText(null);
        jtxtday.setText(null);
        jtxtyear.setText(null);
        jtxtat.setText(null);
        jtxtsemester.setText(null);
        jtxtdt.setText(null);
        jtxttake.setText(null);
        jtxtdate1.setText(null);
        jtxtday2.setText(null);
        jtxtreat1.setText(null);
        jtxtattim.setText(null);
        jtxtsemester1.setText(null);
        jtxtdddep.setText(null);
        jtxtattejhj.setText(null);
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        this.hide();
        Interface frm = new Interface();
        frm.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtnsave;
    private javax.swing.JTextField jtxtat;
    private javax.swing.JTextField jtxtattejhj;
    private javax.swing.JTextField jtxtattim;
    private javax.swing.JTextField jtxtdate1;
    private javax.swing.JTextField jtxtdate6564;
    private javax.swing.JTextField jtxtday;
    private javax.swing.JTextField jtxtday2;
    private javax.swing.JTextField jtxtdddep;
    private javax.swing.JTextField jtxtdt;
    private javax.swing.JTextField jtxtreat1;
    private javax.swing.JTextField jtxtsemester;
    private javax.swing.JTextField jtxtsemester1;
    private javax.swing.JTextField jtxttake;
    private javax.swing.JTextField jtxtyear;
    // End of variables declaration//GEN-END:variables
}
