/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem.system.analysis;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Jishan
 */
public class BillingSearch extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    ResultSet rs;

    /**
     * Creates new form BillingSearch
     */
    public BillingSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtid = new javax.swing.JTextField();
        jtxtname = new javax.swing.JTextField();
        jbtnsearch = new javax.swing.JButton();
        jbtnsearch1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtxtdate = new javax.swing.JTextField();
        jtxtyear = new javax.swing.JTextField();
        jtxtsemester = new javax.swing.JTextField();
        jtxtpayment = new javax.swing.JTextField();
        jtxtmonth = new javax.swing.JTextField();
        jtxtdate1 = new javax.swing.JTextField();
        jtxtkh = new javax.swing.JTextField();
        jtxtpaymentstatus = new javax.swing.JTextField();
        jtxtdjh = new javax.swing.JTextField();
        jtxtjgaa = new javax.swing.JTextField();
        jbtnreset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SUNRISE PARISH PUBLIC SCHOOL SYSTEM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 0, 560, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Billing Search");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 30, 340, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel4.setText("         © 2017 Sunrise Parish Public School System | All Rights Reserved By Sunrise School | Dhaka, Bangladesh-1208 | Phone +88-02-01977239551");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 350, 580, 11);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Billing Information Search By ID-Teacher");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 80, 280, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Billing Information Search By ID-Student");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 210, 270, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Teacher's ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 110, 120, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student's ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 230, 70, 14);

        jtxtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtid);
        jtxtid.setBounds(260, 110, 260, 18);

        jtxtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtname);
        jtxtname.setBounds(260, 230, 260, 18);

        jbtnsearch.setBackground(new java.awt.Color(204, 153, 255));
        jbtnsearch.setText("Search");
        jbtnsearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsearch);
        jbtnsearch.setBounds(550, 110, 90, 20);

        jbtnsearch1.setBackground(new java.awt.Color(204, 153, 255));
        jbtnsearch1.setText("Search");
        jbtnsearch1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsearch1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsearch1);
        jbtnsearch1.setBounds(550, 230, 90, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Billing Information");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 130, 104, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Billing Information");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 250, 130, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 160, 30, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Month");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(240, 160, 50, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Year");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(390, 160, 26, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Semester");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(530, 160, 80, 14);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Payment Status");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(180, 190, 100, 14);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Date");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(100, 270, 40, 14);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Month");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(240, 270, 36, 14);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Year");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(380, 270, 26, 14);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Semester");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(510, 270, 55, 14);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Payment Status");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(180, 300, 91, 14);

        jButton1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 330, 120, 20);

        jButton2.setBackground(new java.awt.Color(204, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 330, 120, 20);

        jtxtdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtdate);
        jtxtdate.setBounds(140, 160, 90, 20);

        jtxtyear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtyear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtyear);
        jtxtyear.setBounds(430, 160, 90, 20);

        jtxtsemester.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsemester.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtsemester);
        jtxtsemester.setBounds(600, 160, 80, 20);

        jtxtpayment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtpayment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtpayment);
        jtxtpayment.setBounds(290, 190, 390, 20);

        jtxtmonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtmonth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtmonthActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtmonth);
        jtxtmonth.setBounds(290, 160, 90, 20);

        jtxtdate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdate1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdate1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtdate1);
        jtxtdate1.setBounds(140, 270, 90, 20);

        jtxtkh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtkh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtkh);
        jtxtkh.setBounds(410, 270, 90, 20);

        jtxtpaymentstatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtpaymentstatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtpaymentstatus);
        jtxtpaymentstatus.setBounds(290, 300, 390, 20);

        jtxtdjh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdjh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtdjh);
        jtxtdjh.setBounds(280, 270, 90, 20);

        jtxtjgaa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtjgaa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jtxtjgaa);
        jtxtjgaa.setBounds(580, 270, 100, 20);

        jbtnreset.setBackground(new java.awt.Color(204, 153, 255));
        jbtnreset.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jbtnreset.setText("Reset");
        jbtnreset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnreset);
        jbtnreset.setBounds(350, 330, 120, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementsystem/system/analysis/shutterstock_167557547.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsearchActionPerformed
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/SystemAnalysis", "Jishan", "Jishan");
            ps = con.prepareStatement("SELECT * FROM JISHAN.BILLINGSECTION where TEACHER_ID=?");
            ps.setInt(1, Integer.parseInt(jtxtid.getText()));
            rs = ps.executeQuery();

            while (rs.next()) {
                jtxtdate.setText(rs.getString("DATE"));
                jtxtmonth.setText(rs.getString("MONTH"));
                jtxtyear.setText(rs.getString("Y_EAR"));
                jtxtsemester.setText(rs.getString("SEMESTER"));
                jtxtpayment.setText(rs.getString("PAYMENT_STATUS"));
                JOptionPane.showMessageDialog(null, "Congratulations...!!! \nWe can findout your data from our database...!!! \nThank you for using student management system...!!!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnsearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
        Search frm = new Search();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtmonthActionPerformed

    private void jtxtdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdate1ActionPerformed

    private void jbtnsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsearch1ActionPerformed
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/SystemAnalysis", "Jishan", "Jishan");
            ps = con.prepareStatement("SELECT * FROM JISHAN.BILLINGSECTION where STUDENT_ID=?");
            ps.setInt(1, Integer.parseInt(jtxtname.getText()));
            rs = ps.executeQuery();

            while (rs.next()) {
                jtxtdate1.setText(rs.getString("STUDENT_DATE"));
                jtxtdjh.setText(rs.getString("STUDENT_MONTH"));
                jtxtkh.setText(rs.getString("STUDENT_YEAR"));
                jtxtjgaa.setText(rs.getString("STUDENT_SEMESTER"));
                jtxtpaymentstatus.setText(rs.getString("STUDENT_STATUS"));
                JOptionPane.showMessageDialog(null, "Congratulations...!!! \nWe can findout your data from our database...!!! \nThank you for using student management system...!!!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnsearch1ActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        jtxtname.setText(null);
        jtxtdate.setText(null);
        jtxtmonth.setText(null);
        jtxtyear.setText(null);
        jtxtsemester.setText(null);
        jtxtpayment.setText(null);
        jtxtdate1.setText(null);
        jtxtdjh.setText(null);
        jtxtkh.setText(null);
        jtxtjgaa.setText(null);
        jtxtpaymentstatus.setText(null);
        jtxtid.setText(null);
    }//GEN-LAST:event_jbtnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtnsearch;
    private javax.swing.JButton jbtnsearch1;
    private javax.swing.JTextField jtxtdate;
    private javax.swing.JTextField jtxtdate1;
    private javax.swing.JTextField jtxtdjh;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtjgaa;
    private javax.swing.JTextField jtxtkh;
    private javax.swing.JTextField jtxtmonth;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtpayment;
    private javax.swing.JTextField jtxtpaymentstatus;
    private javax.swing.JTextField jtxtsemester;
    private javax.swing.JTextField jtxtyear;
    // End of variables declaration//GEN-END:variables
}
