/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem.system.analysis;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jishan
 */
public class Billing extends javax.swing.JFrame {

    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtdate = new javax.swing.JTextField();
        jtxtmonth = new javax.swing.JTextField();
        jtxtyear = new javax.swing.JTextField();
        jtxtpayment = new javax.swing.JTextField();
        jtxttk = new javax.swing.JTextField();
        jtxtpay = new javax.swing.JTextField();
        jtxtpaid = new javax.swing.JTextField();
        jtxtsemester = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jtxtdate1 = new javax.swing.JTextField();
        jtxtdjh = new javax.swing.JTextField();
        jtxtkh = new javax.swing.JTextField();
        jtxtjgaa = new javax.swing.JTextField();
        jtxtutyry = new javax.swing.JTextField();
        jtxtytytyt = new javax.swing.JTextField();
        jtxtpaymentstatus = new javax.swing.JTextField();
        jtxtgyrtrtr = new javax.swing.JTextField();
        jtxtkhjhjhjkh = new javax.swing.JTextField();
        jbtnsave = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jbtnexit = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jbtnback = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jtxtid = new javax.swing.JTextField();
        jtxtname = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SUNRISE PARISH PUBLIC SCHOOL SYSTEM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 0, 570, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Billing Section");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 30, 160, 27);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Billing Information Posting-Teacher");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 80, 250, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Billing Information Posting-Student");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 320, 270, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 110, 34, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Month");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 140, 35, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Year");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(300, 140, 25, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Semester");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 170, 52, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Teaching Subject");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 200, 96, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Payment = ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 220, 65, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Payable");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(110, 240, 73, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total Paid");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(340, 240, 54, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Payment Status :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(80, 270, 100, 15);

        jtxtdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtdate);
        jtxtdate.setBounds(130, 110, 150, 18);

        jtxtmonth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtmonth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtmonth);
        jtxtmonth.setBounds(130, 140, 150, 18);

        jtxtyear.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtyear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtyear);
        jtxtyear.setBounds(340, 140, 200, 18);

        jtxtpayment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtpayment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtpayment);
        jtxtpayment.setBounds(190, 270, 350, 30);

        jtxttk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxttk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxttk);
        jtxttk.setBounds(190, 200, 350, 18);

        jtxtpay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtpay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtpay);
        jtxtpay.setBounds(190, 240, 140, 18);

        jtxtpaid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtpaid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtpaid);
        jtxtpaid.setBounds(400, 240, 140, 18);

        jtxtsemester.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsemester.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsemester);
        jtxtsemester.setBounds(140, 170, 400, 18);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(80, 350, 40, 15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Month");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(80, 380, 40, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Year");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(310, 380, 25, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Semester");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(80, 410, 52, 15);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("No. of Subject Taking This Semester");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(80, 440, 202, 15);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Subject's Name");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(80, 470, 85, 15);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total Payable");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(110, 510, 73, 15);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Payment Status :");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(80, 530, 120, 15);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Total Paid");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(340, 510, 54, 15);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Payment =");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(80, 490, 61, 15);

        jtxtdate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdate1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtdate1);
        jtxtdate1.setBounds(130, 350, 150, 18);

        jtxtdjh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdjh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtdjh);
        jtxtdjh.setBounds(130, 380, 150, 20);

        jtxtkh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtkh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtkh);
        jtxtkh.setBounds(350, 380, 190, 18);

        jtxtjgaa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtjgaa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtjgaa);
        jtxtjgaa.setBounds(140, 410, 400, 18);

        jtxtutyry.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtutyry.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtutyry);
        jtxtutyry.setBounds(190, 510, 140, 18);

        jtxtytytyt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtytytyt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtytytyt);
        jtxtytytyt.setBounds(400, 510, 140, 18);

        jtxtpaymentstatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtpaymentstatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtpaymentstatus);
        jtxtpaymentstatus.setBounds(170, 550, 370, 18);

        jtxtgyrtrtr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtgyrtrtr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtgyrtrtr);
        jtxtgyrtrtr.setBounds(180, 470, 360, 18);

        jtxtkhjhjhjkh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtkhjhjhjkh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtkhjhjhjkh);
        jtxtkhjhjhjkh.setBounds(290, 440, 250, 18);

        jbtnsave.setBackground(new java.awt.Color(153, 153, 255));
        jbtnsave.setText("Save");
        jbtnsave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnsave);
        jbtnsave.setBounds(640, 180, 100, 30);

        jbtnreset.setBackground(new java.awt.Color(153, 153, 255));
        jbtnreset.setText("Reset");
        jbtnreset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnreset);
        jbtnreset.setBounds(640, 230, 100, 30);

        jbtnexit.setBackground(new java.awt.Color(153, 153, 255));
        jbtnexit.setText("Exit");
        jbtnexit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnexit);
        jbtnexit.setBounds(640, 330, 100, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("         © 2017 Sunrise Parish Public School System | All Rights Reserved By Sunrise School | Dhaka, Bangladesh-1208 | Phone +88-02-01977239551");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(60, 580, 680, 11);

        jbtnback.setBackground(new java.awt.Color(153, 153, 255));
        jbtnback.setText("Back");
        jbtnback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnback);
        jbtnback.setBounds(640, 280, 100, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Teacher's ID");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(290, 110, 80, 14);

        jtxtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtid);
        jtxtid.setBounds(370, 110, 170, 18);

        jtxtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtname.setToolTipText("");
        jtxtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtname);
        jtxtname.setBounds(370, 350, 170, 18);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Student's ID");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(290, 350, 69, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementsystem/system/analysis/ttght.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsaveActionPerformed
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/SystemAnalysis", "Jishan", "Jishan");
            PreparedStatement ps = conn.prepareStatement("insert into BILLINGSECTION values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, jtxtdate.getText());
            ps.setString(2, jtxtmonth.getText());
            ps.setString(3, jtxtyear.getText());
            ps.setString(4, jtxtsemester.getText());
            ps.setString(5, jtxttk.getText());
            ps.setString(6, jtxtpay.getText());
            ps.setString(7, jtxtpaid.getText());
            ps.setString(8, jtxtpayment.getText());
            ps.setString(9, jtxtdate1.getText());
            ps.setString(10, jtxtdjh.getText());
            ps.setString(11, jtxtkh.getText());
            ps.setString(12, jtxtjgaa.getText());
            ps.setString(13, jtxtkhjhjhjkh.getText());
            ps.setString(14, jtxtgyrtrtr.getText());
            ps.setString(15, jtxtutyry.getText());
            ps.setString(16, jtxtytytyt.getText());
            ps.setString(17, jtxtpaymentstatus.getText());
            ps.setString(18, jtxtname.getText());
            ps.setString(19, jtxtid.getText());
            ps.executeUpdate();
            conn.close();
            JOptionPane.showMessageDialog(null, "Congratulations...!!! \nYour data has been successfully store in our database...!!! \nThank you for using student management system...!!!");
            System.out.println("Congratulations...!!! Data save successfully...!!!");
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnsaveActionPerformed

    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        jtxtdate.setText(null);
        jtxtmonth.setText(null);
        jtxtyear.setText(null);
        jtxtsemester.setText(null);
        jtxttk.setText(null);
        jtxtpay.setText(null);
        jtxtpaid.setText(null);
        jtxtpayment.setText(null);
        jtxtdate1.setText(null);
        jtxtdjh.setText(null);
        jtxtkh.setText(null);
        jtxtjgaa.setText(null);
        jtxtkhjhjhjkh.setText(null);
        jtxtgyrtrtr.setText(null);
        jtxtutyry.setText(null);
        jtxtytytyt.setText(null);
        jtxtpaymentstatus.setText(null);
        jtxtname.setText(null);
        jtxtid.setText(null);
    }//GEN-LAST:event_jbtnresetActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        this.hide();
        Interface frm = new Interface();
        frm.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtnsave;
    private javax.swing.JTextField jtxtdate;
    private javax.swing.JTextField jtxtdate1;
    private javax.swing.JTextField jtxtdjh;
    private javax.swing.JTextField jtxtgyrtrtr;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtjgaa;
    private javax.swing.JTextField jtxtkh;
    private javax.swing.JTextField jtxtkhjhjhjkh;
    private javax.swing.JTextField jtxtmonth;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtpaid;
    private javax.swing.JTextField jtxtpay;
    private javax.swing.JTextField jtxtpayment;
    private javax.swing.JTextField jtxtpaymentstatus;
    private javax.swing.JTextField jtxtsemester;
    private javax.swing.JTextField jtxttk;
    private javax.swing.JTextField jtxtutyry;
    private javax.swing.JTextField jtxtyear;
    private javax.swing.JTextField jtxtytytyt;
    // End of variables declaration//GEN-END:variables
}
