/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem.system.analysis;

/**
 *
 * @author Jishan
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnai = new javax.swing.JButton();
        jbtnti = new javax.swing.JButton();
        jbtnjis = new javax.swing.JButton();
        jbtnrep = new javax.swing.JButton();
        jbtnattendance = new javax.swing.JButton();
        jbtnsearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("SUNRISE PARISH PUBLIC SCHOOL SYSTEM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 10, 760, 41);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Student Management System");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 50, 520, 29);

        jbtnai.setBackground(new java.awt.Color(0, 153, 153));
        jbtnai.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jbtnai.setText("Add New Student Information");
        jbtnai.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaiActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnai);
        jbtnai.setBounds(10, 200, 460, 31);

        jbtnti.setBackground(new java.awt.Color(51, 0, 204));
        jbtnti.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jbtnti.setText("Add Teacher Information");
        jbtnti.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntiActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnti);
        jbtnti.setBounds(70, 270, 460, 30);

        jbtnjis.setBackground(new java.awt.Color(153, 0, 102));
        jbtnjis.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jbtnjis.setText("Billing Section");
        jbtnjis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnjis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnjisActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnjis);
        jbtnjis.setBounds(130, 340, 460, 30);

        jbtnrep.setBackground(new java.awt.Color(255, 204, 51));
        jbtnrep.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jbtnrep.setText("Result Entry Section");
        jbtnrep.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrepActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnrep);
        jbtnrep.setBounds(190, 410, 460, 31);

        jbtnattendance.setBackground(new java.awt.Color(51, 255, 51));
        jbtnattendance.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jbtnattendance.setText("Attendance Information");
        jbtnattendance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnattendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnattendanceActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnattendance);
        jbtnattendance.setBounds(250, 480, 460, 31);

        jbtnsearch.setBackground(new java.awt.Color(102, 153, 0));
        jbtnsearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jbtnsearch.setText("Search Option");
        jbtnsearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnsearch);
        jbtnsearch.setBounds(310, 550, 460, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("\"Education for a bright future\"");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 650, 350, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("         © 2017 Sunrise Parish Public School System | All Rights Reserved By Sunrise School | Dhaka, Bangladesh-1208 | Phone +88-02-01977239551");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-10, 680, 780, 13);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Choose One Option From Below Option...........");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 150, 540, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementsystem/system/analysis/school-management-system.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 780, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrepActionPerformed
        ResultEntry l = new ResultEntry();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnrepActionPerformed

    private void jbtnattendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnattendanceActionPerformed
        Attendance k = new Attendance();
        k.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnattendanceActionPerformed

    private void jbtnaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaiActionPerformed
        AddStudentInformation b = new AddStudentInformation();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnaiActionPerformed

    private void jbtntiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntiActionPerformed
        AddTeacherInfo c = new AddTeacherInfo();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtntiActionPerformed

    private void jbtnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsearchActionPerformed
        Search d = new Search();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnsearchActionPerformed

    private void jbtnjisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnjisActionPerformed
        Billing f = new Billing();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnjisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnai;
    private javax.swing.JButton jbtnattendance;
    private javax.swing.JButton jbtnjis;
    private javax.swing.JButton jbtnrep;
    private javax.swing.JButton jbtnsearch;
    private javax.swing.JButton jbtnti;
    // End of variables declaration//GEN-END:variables
}
