/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem.system.analysis;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Jishan
 */
public class ResultEntry extends javax.swing.JFrame {

    /**
     * Creates new form ResultEntry
     */
    public ResultEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jtxtsub1 = new javax.swing.JTextField();
        jtxtsubb1 = new javax.swing.JTextField();
        sub2 = new javax.swing.JTextField();
        sub1 = new javax.swing.JTextField();
        lab2 = new javax.swing.JTextField();
        lab1 = new javax.swing.JTextField();
        jtxtsubb3 = new javax.swing.JTextField();
        sub4 = new javax.swing.JTextField();
        sub5 = new javax.swing.JTextField();
        jtxtsubb2 = new javax.swing.JTextField();
        sub3 = new javax.swing.JTextField();
        jtxtlabb1 = new javax.swing.JTextField();
        jtxtsubb4 = new javax.swing.JTextField();
        jtxtlab1 = new javax.swing.JTextField();
        lab3 = new javax.swing.JTextField();
        jtxtsub5 = new javax.swing.JTextField();
        jtxtsub3 = new javax.swing.JTextField();
        jtxtsub2 = new javax.swing.JTextField();
        jtxtlab2 = new javax.swing.JTextField();
        jtxtlabb2 = new javax.swing.JTextField();
        jtxtsub4 = new javax.swing.JTextField();
        jtxtsubb5 = new javax.swing.JTextField();
        jtxtlab3 = new javax.swing.JTextField();
        jtxtlabb3 = new javax.swing.JTextField();
        jtxtid = new javax.swing.JTextField();
        jtxtsem = new javax.swing.JTextField();
        jtxtdept = new javax.swing.JTextField();
        jtxtname = new javax.swing.JTextField();
        jtxtadv = new javax.swing.JTextField();
        jbtnsave = new javax.swing.JButton();
        jbtnreset = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jtxtresult = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SUNRISE PARISH PUBLIC SCHOOL SYSTEM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 0, 610, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Result Entry");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 30, 270, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("         © 2017 Sunrise Parish Public School System | All Rights Reserved By Sunrise School | Dhaka, Bangladesh-1208 | Phone +88-02-01977239551");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 580, 670, 13);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 70, 100, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 100, 90, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Subject-Wise Result Entry :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 220, 210, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Semester");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 160, 80, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Subject-1");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 280, 80, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Advisor Name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 190, 74, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Subject-3");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 360, 60, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Lab-3");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 530, 40, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lab-1");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(50, 470, 40, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Subject-4");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 400, 60, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Department");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(50, 130, 80, 15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Lab-2");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(50, 500, 40, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Subject-5");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(50, 440, 60, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Subject-2");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(50, 320, 60, 15);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Result");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(600, 250, 50, 15);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Course Name");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(310, 250, 79, 15);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Course Code");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(130, 250, 90, 15);

        jtxtsub1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsub1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsub1);
        jtxtsub1.setBounds(120, 280, 100, 18);

        jtxtsubb1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsubb1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsubb1);
        jtxtsubb1.setBounds(270, 280, 180, 18);

        sub2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sub2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(sub2);
        sub2.setBounds(510, 320, 240, 18);

        sub1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sub1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(sub1);
        sub1.setBounds(510, 280, 240, 18);

        lab2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lab2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lab2);
        lab2.setBounds(510, 500, 240, 18);

        lab1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lab1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lab1);
        lab1.setBounds(510, 470, 240, 18);

        jtxtsubb3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsubb3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsubb3);
        jtxtsubb3.setBounds(270, 360, 180, 18);

        sub4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sub4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(sub4);
        sub4.setBounds(510, 400, 240, 18);

        sub5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sub5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(sub5);
        sub5.setBounds(510, 440, 240, 18);

        jtxtsubb2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsubb2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsubb2);
        jtxtsubb2.setBounds(270, 320, 180, 18);

        sub3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sub3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(sub3);
        sub3.setBounds(510, 360, 240, 18);

        jtxtlabb1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtlabb1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtlabb1);
        jtxtlabb1.setBounds(270, 470, 180, 18);

        jtxtsubb4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsubb4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsubb4);
        jtxtsubb4.setBounds(270, 400, 180, 18);

        jtxtlab1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtlab1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtlab1);
        jtxtlab1.setBounds(120, 470, 100, 18);

        lab3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lab3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lab3);
        lab3.setBounds(510, 530, 240, 18);

        jtxtsub5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsub5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsub5);
        jtxtsub5.setBounds(120, 440, 100, 18);

        jtxtsub3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsub3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsub3);
        jtxtsub3.setBounds(120, 360, 100, 18);

        jtxtsub2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsub2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsub2);
        jtxtsub2.setBounds(120, 320, 100, 18);

        jtxtlab2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtlab2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtlab2);
        jtxtlab2.setBounds(120, 500, 100, 18);

        jtxtlabb2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtlabb2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtlabb2);
        jtxtlabb2.setBounds(270, 500, 180, 18);

        jtxtsub4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsub4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsub4);
        jtxtsub4.setBounds(120, 400, 100, 18);

        jtxtsubb5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsubb5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsubb5);
        jtxtsubb5.setBounds(270, 440, 180, 18);

        jtxtlab3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtlab3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtlab3);
        jtxtlab3.setBounds(120, 530, 100, 18);

        jtxtlabb3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtlabb3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtlabb3);
        jtxtlabb3.setBounds(270, 530, 180, 18);

        jtxtid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtid);
        jtxtid.setBounds(150, 70, 610, 18);

        jtxtsem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtsem);
        jtxtsem.setBounds(150, 160, 610, 18);

        jtxtdept.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdept.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtdept);
        jtxtdept.setBounds(150, 130, 610, 18);

        jtxtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtname);
        jtxtname.setBounds(150, 100, 610, 18);

        jtxtadv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtadv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtadv);
        jtxtadv.setBounds(150, 190, 240, 18);

        jbtnsave.setBackground(new java.awt.Color(0, 204, 204));
        jbtnsave.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtnsave.setText("Save");
        jbtnsave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnsave);
        jbtnsave.setBounds(70, 560, 120, 17);

        jbtnreset.setBackground(new java.awt.Color(0, 204, 204));
        jbtnreset.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbtnreset.setText("Reset");
        jbtnreset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnresetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnreset);
        jbtnreset.setBounds(270, 560, 120, 17);

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setText("Exit");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(650, 560, 120, 17);

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setText("Back");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(470, 560, 120, 17);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Result");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(430, 190, 50, 15);

        jtxtresult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtresult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtresult);
        jtxtresult.setBounds(490, 190, 270, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementsystem/system/analysis/ttght.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsaveActionPerformed
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/SystemAnalysis", "Jishan", "Jishan");
            PreparedStatement ps = conn.prepareStatement("insert into RESULT values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, jtxtid.getText());
            ps.setString(2, jtxtname.getText());
            ps.setString(3, jtxtdept.getText());
            ps.setString(4, jtxtsem.getText());
            ps.setString(5, jtxtadv.getText());
            ps.setString(6, jtxtsub1.getText());
            ps.setString(7, jtxtsub2.getText());
            ps.setString(8, jtxtsub3.getText());
            ps.setString(9, jtxtsub4.getText());
            ps.setString(10, jtxtsub5.getText());
            ps.setString(11, jtxtlab1.getText());
            ps.setString(12, jtxtlab2.getText());
            ps.setString(13, jtxtlab3.getText());
            ps.setString(14, jtxtsubb1.getText());
            ps.setString(15, jtxtsubb2.getText());
            ps.setString(16, jtxtsubb3.getText());
            ps.setString(17, jtxtsubb4.getText());
            ps.setString(18, jtxtsubb5.getText());
            ps.setString(19, jtxtlabb1.getText());
            ps.setString(20, jtxtlabb2.getText());
            ps.setString(21, jtxtlabb3.getText());
            ps.setString(22, jtxtresult.getText());
            ps.setString(23, sub1.getText());
            ps.setString(24, sub2.getText());
            ps.setString(25, sub3.getText());
            ps.setString(26, sub4.getText());
            ps.setString(27, sub5.getText());
            ps.setString(28, lab1.getText());
            ps.setString(29, lab2.getText());
            ps.setString(30, lab3.getText());
            ps.executeUpdate();
            conn.close();
            JOptionPane.showMessageDialog(null, "Congratulations...!!! \nYour data has been successfully store in our database...!!! \nThank you for using student management system...!!!");
            System.out.println("Congratulations...!!! Data save successfully...!!!");
            ps.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnsaveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.hide();
        Interface frm = new Interface();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbtnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnresetActionPerformed
        jtxtid.setText(null);
        jtxtname.setText(null);
        jtxtdept.setText(null);
        jtxtsem.setText(null);
        jtxtadv.setText(null);
        jtxtsub1.setText(null);
        jtxtsub2.setText(null);
        jtxtsub3.setText(null);
        jtxtsub4.setText(null);
        jtxtsub5.setText(null);
        jtxtlab1.setText(null);
        jtxtlab2.setText(null);
        jtxtlab3.setText(null);
        jtxtsubb1.setText(null);
        jtxtsubb2.setText(null);
        jtxtsubb3.setText(null);
        jtxtsubb4.setText(null);
        jtxtsubb5.setText(null);
        jtxtlabb1.setText(null);
        jtxtlabb2.setText(null);
        jtxtlabb3.setText(null);
        jtxtresult.setText(null);
        sub1.setText(null);
        sub2.setText(null);
        sub3.setText(null);
        sub4.setText(null);
        sub5.setText(null);
        lab1.setText(null);
        lab2.setText(null);
        lab3.setText(null);
    }//GEN-LAST:event_jbtnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnreset;
    private javax.swing.JButton jbtnsave;
    private javax.swing.JTextField jtxtadv;
    private javax.swing.JTextField jtxtdept;
    private javax.swing.JTextField jtxtid;
    private javax.swing.JTextField jtxtlab1;
    private javax.swing.JTextField jtxtlab2;
    private javax.swing.JTextField jtxtlab3;
    private javax.swing.JTextField jtxtlabb1;
    private javax.swing.JTextField jtxtlabb2;
    private javax.swing.JTextField jtxtlabb3;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtresult;
    private javax.swing.JTextField jtxtsem;
    private javax.swing.JTextField jtxtsub1;
    private javax.swing.JTextField jtxtsub2;
    private javax.swing.JTextField jtxtsub3;
    private javax.swing.JTextField jtxtsub4;
    private javax.swing.JTextField jtxtsub5;
    private javax.swing.JTextField jtxtsubb1;
    private javax.swing.JTextField jtxtsubb2;
    private javax.swing.JTextField jtxtsubb3;
    private javax.swing.JTextField jtxtsubb4;
    private javax.swing.JTextField jtxtsubb5;
    private javax.swing.JTextField lab1;
    private javax.swing.JTextField lab2;
    private javax.swing.JTextField lab3;
    private javax.swing.JTextField sub1;
    private javax.swing.JTextField sub2;
    private javax.swing.JTextField sub3;
    private javax.swing.JTextField sub4;
    private javax.swing.JTextField sub5;
    // End of variables declaration//GEN-END:variables
}
