/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem.system.analysis;

/**
 *
 * @author Jishan
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnsr = new javax.swing.JButton();
        jbtnti = new javax.swing.JButton();
        jbtnrs = new javax.swing.JButton();
        jbtnbilling = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jbtnexit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search Option");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 40, 480, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SUNRISE PARISH PUBLIC SCHOOL SYSTEM");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 0, 630, 44);

        jbtnsr.setBackground(new java.awt.Color(0, 204, 204));
        jbtnsr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnsr.setText("Student Information");
        jbtnsr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsrActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsr);
        jbtnsr.setBounds(20, 120, 290, 27);

        jbtnti.setBackground(new java.awt.Color(255, 0, 0));
        jbtnti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnti.setText("Teacher Information");
        jbtnti.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntiActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnti);
        jbtnti.setBounds(110, 170, 290, 27);

        jbtnrs.setBackground(new java.awt.Color(204, 255, 0));
        jbtnrs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnrs.setText("Result Search");
        jbtnrs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnrs);
        jbtnrs.setBounds(200, 220, 290, 30);

        jbtnbilling.setBackground(new java.awt.Color(0, 0, 204));
        jbtnbilling.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtnbilling.setText("Billing");
        jbtnbilling.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnbilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbillingActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnbilling);
        jbtnbilling.setBounds(300, 270, 290, 30);

        jbtnback.setBackground(new java.awt.Color(153, 255, 153));
        jbtnback.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnback.setText("Back");
        jbtnback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnback);
        jbtnback.setBounds(80, 330, 130, 23);

        jbtnexit.setBackground(new java.awt.Color(153, 255, 153));
        jbtnexit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnexit.setText("Exit");
        jbtnexit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnexit);
        jbtnexit.setBounds(520, 330, 130, 21);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("         © 2017 Sunrise Parish Public School System | All Rights Reserved By Sunrise School | Dhaka, Bangladesh-1208 | Phone +88-02-01977239551");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 350, 590, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementsystem/system/analysis/school.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        this.hide();
        Interface frm = new Interface();
        frm.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    private void jbtnsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsrActionPerformed
        Studentall e = new Studentall();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnsrActionPerformed

    private void jbtntiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntiActionPerformed
        TeacherAll j = new TeacherAll();
        j.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtntiActionPerformed

    private void jbtnbillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbillingActionPerformed
        BillingSearch x = new BillingSearch();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnbillingActionPerformed

    private void jbtnrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrsActionPerformed
        ResultSearch z = new ResultSearch();
        z.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnrsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnbilling;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnrs;
    private javax.swing.JButton jbtnsr;
    private javax.swing.JButton jbtnti;
    // End of variables declaration//GEN-END:variables
}
