/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem.system.analysis;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Jishan
 */
public class StudentSearch extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    ResultSet rs;

    /**
     * Creates new form StudentSearch
     */
    public StudentSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jbtnsearch = new javax.swing.JButton();
        jbtnexit = new javax.swing.JButton();
        jbtnback = new javax.swing.JButton();
        jtxtfullN = new javax.swing.JTextField();
        jtxtFather = new javax.swing.JTextField();
        jtxtMother = new javax.swing.JTextField();
        jtxtdob = new javax.swing.JTextField();
        jtxtcontc = new javax.swing.JTextField();
        Jtxtpsc = new javax.swing.JTextField();
        JTXTJSC = new javax.swing.JTextField();
        jtxtssc = new javax.swing.JTextField();
        jtxtdistrict = new javax.swing.JTextField();
        jtxtlol = new javax.swing.JTextField();
        jtxybloodg = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SUNRISE PARISH PUBLIC SCHOOL SYSTEM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, -10, 590, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Information Search");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 30, 410, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Please Search Information By ID :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 70, 250, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student's ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 100, 110, 16);

        jtxtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtname);
        jtxtname.setBounds(230, 100, 400, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student's Information :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 150, 230, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student's Full Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 180, 150, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date of Birth");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 210, 110, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Father's Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(100, 240, 130, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mother's Name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(100, 270, 110, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contact Number");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(100, 300, 150, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PSC/PEC Result");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(100, 330, 130, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("JSC Result");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(100, 360, 130, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("SSC Result");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(100, 390, 90, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Permenant Address :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(100, 450, 160, 16);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("District :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(250, 480, 70, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Present Address :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(100, 510, 150, 16);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Blood Group");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(100, 420, 130, 14);

        jbtnsearch.setBackground(new java.awt.Color(0, 51, 153));
        jbtnsearch.setText("Search");
        jbtnsearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnsearch);
        jbtnsearch.setBounds(670, 100, 73, 23);

        jbtnexit.setBackground(new java.awt.Color(0, 51, 153));
        jbtnexit.setText("Exit");
        jbtnexit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnexit);
        jbtnexit.setBounds(500, 550, 90, 19);

        jbtnback.setBackground(new java.awt.Color(0, 51, 153));
        jbtnback.setText("Back");
        jbtnback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnback);
        jbtnback.setBounds(140, 550, 90, 19);

        jtxtfullN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtfullN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtfullN);
        jtxtfullN.setBounds(250, 180, 380, 20);

        jtxtFather.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFather.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtFather);
        jtxtFather.setBounds(250, 240, 380, 18);

        jtxtMother.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMother.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtMother);
        jtxtMother.setBounds(250, 270, 380, 18);

        jtxtdob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdob.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtdob);
        jtxtdob.setBounds(250, 210, 380, 18);

        jtxtcontc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcontc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtcontc);
        jtxtcontc.setBounds(250, 300, 380, 18);

        Jtxtpsc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Jtxtpsc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(Jtxtpsc);
        Jtxtpsc.setBounds(250, 330, 380, 18);

        JTXTJSC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTXTJSC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(JTXTJSC);
        JTXTJSC.setBounds(250, 360, 380, 18);

        jtxtssc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtssc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtssc);
        jtxtssc.setBounds(250, 390, 380, 18);

        jtxtdistrict.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdistrict.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtdistrict);
        jtxtdistrict.setBounds(310, 520, 170, 18);

        jtxtlol.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtlol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxtlol);
        jtxtlol.setBounds(310, 480, 170, 18);

        jtxybloodg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxybloodg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jtxybloodg);
        jtxybloodg.setBounds(250, 420, 380, 18);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("District :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(250, 520, 60, 15);

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("         © 2017 Sunrise Parish Public School System | All Rights Reserved By Sunrise School | Dhaka, Bangladesh-1208 | Phone +88-02-01977239551");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(30, 570, 700, 14);

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setText("Reset");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 550, 90, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentmanagementsystem/system/analysis/ttght.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 780, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsearchActionPerformed
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/SystemAnalysis", "Jishan", "Jishan");
            ps = con.prepareStatement("SELECT * FROM JISHAN.ADDNEWSTUDENT where ID_NUMBER=?");
            ps.setInt(1, Integer.parseInt(jtxtname.getText()));
            rs = ps.executeQuery();

            while (rs.next()) {
                jtxtfullN.setText(rs.getString("FULL_NAME"));
                jtxtdob.setText(rs.getString("DATE_OF_BIRTH"));
                jtxtFather.setText(rs.getString("FATHER_NAME"));
                jtxtMother.setText(rs.getString("MOTHER_NAME"));
                jtxtcontc.setText(rs.getString("CONTACT_NUMBER"));
                jtxybloodg.setText(rs.getString("BLOOD_GROUP"));
                Jtxtpsc.setText(rs.getString("PSC_OR_PEC"));
                JTXTJSC.setText(rs.getString("JSC"));
                jtxtssc.setText(rs.getString("SSC"));
                jtxtlol.setText(rs.getString("P_DISTRICT"));
                jtxtdistrict.setText(rs.getString("PR_DISTRICT"));
                JOptionPane.showMessageDialog(null, "Congratulations...!!! \nWe can findout your data from our database...!!! \nThank you for using student management system...!!!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jbtnsearchActionPerformed

    private void jbtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackActionPerformed
        this.hide();
        Studentall frm = new Studentall();
        frm.setVisible(true);
    }//GEN-LAST:event_jbtnbackActionPerformed

    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jtxtname.setText(null);
        jtxtfullN.setText(null);
        jtxtdob.setText(null);
        jtxtFather.setText(null);
        jtxtMother.setText(null);
        jtxtcontc.setText(null);
        jtxybloodg.setText(null);
        Jtxtpsc.setText(null);
        JTXTJSC.setText(null);
        jtxtssc.setText(null);
        jtxtlol.setText(null);
        jtxtdistrict.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTXTJSC;
    private javax.swing.JTextField Jtxtpsc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnback;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnsearch;
    private javax.swing.JTextField jtxtFather;
    private javax.swing.JTextField jtxtMother;
    private javax.swing.JTextField jtxtcontc;
    private javax.swing.JTextField jtxtdistrict;
    private javax.swing.JTextField jtxtdob;
    private javax.swing.JTextField jtxtfullN;
    private javax.swing.JTextField jtxtlol;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtssc;
    private javax.swing.JTextField jtxybloodg;
    // End of variables declaration//GEN-END:variables
}
